name: "Setup"
description: "Setup"
inputs:
  tcommon-deploy-key:
    description: 'The deploy key for tensor-common-rs'
    required: true
runs:
  using: "composite"
  steps:
      - run: git submodule update --init --recursive --depth 1
        shell: bash

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ inputs.tcommon-deploy-key }}