[features]
# Enable if we want to figure out pda-derivation.
seeds = false
skip-lint = false
[programs.localnet]
tensorswap = "TSWAPaqyCSx2KABk68Shruf4rp7CxcNi8hAsbdwmHbN"
tensor_whitelist = "TL1ST2iRBzuGTqLn1KXnGdSnEow62BzPnGiqyRXhWtW"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# eg TESTS_GLOB='tests/tswap/buy.spec.ts anchor test (omit TESTS_GLOB to run all tests)
test = "bash scripts/anchor_test.sh"