[features]
# Enable if we want to figure out pda-derivation.
seeds = false
skip-lint = false
[programs.localnet]
tensorswap = "EcBj1yGnNmya7uGjkrroX8jupyoJn29uTGEk5jv21WPA"
tensor_whitelist = "CyrMiKJphasn4kZLzMFG7cR9bZJ1rifGF37uSpJRxVi6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# parallel mode, doesn't work b/c:
# (1) we can't check fee vault in parallel, b/c
# (2) we're limited to 1 TSwap, b/c
# (3) cfg_attr does not work with account(init) apparently...
# test = "yarn run ts-mocha --parallel --jobs 100 ./tsconfig.json -t 100000 tests/**/*.ts"
# non-parallel mode (for .only)
test = "yarn run ts-mocha -p ./tsconfig.json -t 100000 tests/tswap/**/*.ts"