[features]
# Enable if we want to figure out pda-derivation.
seeds = false
skip-lint = false
[programs.localnet]
tensorswap = "TSWAPaqyCSx2KABk68Shruf4rp7CxcNi8hAsbdwmHbN"
tensor_whitelist = "TL1ST2iRBzuGTqLn1KXnGdSnEow62BzPnGiqyRXhWtW"
tensor_bid = "TB1Dqt8JeKQh7RLDzfYDJsq8KS4fS2yt87avRjyRxMv"

# (!!) Sync deps target dirs with 'cache_cargo/action.yaml'!
# From https://github.com/armaniferrante/auction-house/blob/45518c16f00c68509e06432925403046f2b64463/Anchor.toml
# Required for tests.
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-mpl/token-metadata/target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
program = "./deps/metaplex-auth/programs/token-auth-rules/target/deploy/mpl_token_auth_rules.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "tests/test-keypair.json"

[scripts]
# eg TESTS_GLOB='tests/tswap/buy.spec.ts anchor test (omit TESTS_GLOB to run all tests)
test = "bash scripts/anchor_test.sh"
