[features]
# Enable if we want to figure out pda-derivation.
seeds = false
skip-lint = false
[programs.localnet]
tensorswap = "TSWAPaqyCSx2KABk68Shruf4rp7CxcNi8hAsbdwmHbN"
tensor_whitelist = "TL1ST2iRBzuGTqLn1KXnGdSnEow62BzPnGiqyRXhWtW"
tensor_bid = "TB1Dqt8JeKQh7RLDzfYDJsq8KS4fS2yt87avRjyRxMv"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# From https://github.com/armaniferrante/auction-house/blob/45518c16f00c68509e06432925403046f2b64463/Anchor.toml
# Required for tests.
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "tests/test-keypair.json"

[scripts]
# eg TESTS_GLOB='tests/tswap/buy.spec.ts anchor test (omit TESTS_GLOB to run all tests)
test = "bash scripts/anchor_test.sh"