[package]
name = "tensor_whitelist"
version = "0.2.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tensor_whitelist"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []

[dependencies]
anchor-lang = { version="0.26.0", features=["init-if-needed"] }
anchor-spl = "0.26.0"
mpl-token-metadata = { version="1.8.3", features = [ "no-entrypoint" ] }
vipers = {path= '../../lib/vipers' }
merkle_proof = {path= '../../lib/merkle_proof' }
