[package]
name = "tensorswap"
version = "0.2.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tensorswap"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
testing = []

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = { version = "0.25.0", features =  ["default", "metadata"] }
mpl-token-metadata = { version="1.3.6", features = [ "no-entrypoint" ] }
vipers = "2.0.6"
spl-math = { version = "0.1.0", features = [ "no-entrypoint" ] }
tensor_whitelist = { path = '../tensor_whitelist', features = ["cpi"] }
static_assertions = "1.1.0"
merkle_proof = {path='../../lib/merkle_proof'}