name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  test-rust:
    name: Rust Tests
    runs-on: [self-hosted, linux, x64, solana]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test

      - uses: ./.github/actions/git-diff/

  build-all:
    name: Build all programs
    runs-on: [self-hosted, linux, x64, solana]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup/
        with:
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}
      - uses: ./.github/actions/cache-cargo/
      - run: yarn build:test
      # This ensures the IDL generated matches what's checked in!
      - uses: ./.github/actions/git-diff/

      - uses: actions/upload-artifact@v2
        with:
          name: target-artifact
          path: ./target/

  typescript-checks:
    name: Typescript checks
    runs-on: [self-hosted, linux, x64, solana]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - run: yarn build:ts
        name: Typechecks

  test-typescript:
    needs: build-all
    name: Test ${{ matrix.node.glob }}
    runs-on: [self-hosted, linux, x64, solana]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node:
          - glob: tests/prices.spec.ts
          - glob: tests/tswap/buy.test.ts
          - glob: tests/tswap/deposit.test.ts
          - glob: tests/tswap/pool.test.ts
          - glob: tests/tswap/sell.test.ts
          - glob: tests/tswap/tswap.test.ts
          - glob: tests/tswap/withdraw.test.ts
          # No need to run
          # - glob: tests/tswap/size.test.ts
          # TODO: temp while figure out space issue
          # - glob: tests/tswap/snipe.test.ts
          - glob: tests/tswap/margin.test.ts
          - glob: tests/tswap/singleListing.test.ts
          - glob: tests/twhitelist/whitelist.test.ts
          - glob: tests/twhitelist/mint_proof.test.ts
          - glob: tests/tbid/tbid.test.ts
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
        with:
          tcommon-deploy-key: ${{ secrets.TENSOR_COMMON_RS_RO_DEPLOY_KEY }}

      - uses: actions/download-artifact@v2
        with:
          name: target-artifact
          path: ./target/

      - run: grep -Evqz 'it.only\(|describe.only\(' ${{ matrix.node.glob }}
        name: No only tests

      - uses: ./.github/actions/cache-cargo/

      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - run: yarn install
      - run: yarn fast-test # fine since we built above
        env:
          TESTS_GLOB: ${{ matrix.node.glob }}
      # This ensures the IDL generated matches what's checked in!
      - uses: ./.github/actions/git-diff/
